# Generated by Django 4.1.1 on 2022-09-21 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escaneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaneo',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_user'),
        ),
        migrations.AddField(
            model_name='escaneo',
            name='date_modify',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_modify'),
        ),
        migrations.AlterField(
            model_name='escaneo',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='escaneo',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='escaneo',
            name='user_creation',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
